//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson2.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int ImportanceId { get; set; }
        public System.DateTime Deadline { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual Importance Importance { get; set; }
    }
}
